[mgr]
prepend_keymap = [
  { on = "q", run = "close", desc = "Close the current tab; if it's the last tab, exit the process instead." },
]

append_keymap = [
  { on = [ "g", "C" ], run = "cd ~/Coding", desc = "Go ~/Coding" },
  { on = [ "g", "D" ], run = "cd ~/Documents", desc = "Go ~/Documents" },
]

